# Generated by Django 4.1 on 2023-04-27 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="hackathonsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("background_image", models.ImageField(upload_to="")),
                ("hackathon_image", models.ImageField(upload_to="")),
                ("type_of_submission", models.CharField(max_length=50)),
                ("startdatetime", models.DateTimeField()),
                ("enddatetime", models.DateTimeField()),
                ("reward_prize", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="hackersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "enrolled_hackathons",
                    models.ManyToManyField(
                        blank=True, default="", to="hackr.hackathonsmodel"
                    ),
                ),
                (
                    "hackerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
