# Generated by Django 4.2 on 2023-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0002_alter_hackathonsmodel_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathonsmodel",
            name="oragniser",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
