# Generated by Django 4.2 on 2023-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0003_hackathonsmodel_oragniser"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathonsmodel",
            name="tagline",
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hackathonsmodel",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
