# Generated by Django 4.2 on 2023-05-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0005_submission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="submission",
            new_name="submissionModel",
        ),
    ]
