# Generated by Django 4.2 on 2023-05-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0006_rename_submission_submissionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionmodel",
            name="github_link",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
