# Generated by Django 4.2 on 2023-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0007_submissionmodel_github_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathonsmodel",
            name="githubrepolink",
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
