# Generated by Django 4.2 on 2023-05-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0008_hackathonsmodel_githubrepolink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hackathonsmodel",
            name="background_image",
        ),
        migrations.AddField(
            model_name="hackathonsmodel",
            name="otherlinks",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
