# Generated by Django 4.2 on 2023-05-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackr", "0011_remove_submissionmodel_github_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackersmodel",
            name="enrolled_hackathons",
            field=models.ManyToManyField(blank=True, to="hackr.hackathonsmodel"),
        ),
        migrations.AlterField(
            model_name="submissionmodel",
            name="submission_file",
            field=models.FileField(blank=True, default="", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="submissionmodel",
            name="submission_link",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
